In [2]:
import import_ipynb
from feature_extractor import compute_audio
from audio_processor import AudioProcessor
import os
import random
import json
import pandas as pd
import time

your mom


In [3]:
data_dir = "/data"
labels_dir = "/labels"
data_dir = os.listdir(os.getcwd()+data_dir)
labels_dir = os.listdir(os.getcwd()+labels_dir)

In [4]:
all_files = [f for f in data_dir]
sampled_files = random.sample(all_files, 50)
sampled_labels = [f + '.json' for f in sampled_files]

In [5]:
sampled_labels

['surah22_part1.mp3.json',
 'surah56_part1.mp3.json',
 'surah11_part7.mp3.json',
 'surah19_part2.mp3.json',
 'surah72_part1.mp3.json',
 'surah96_part1.mp3.json',
 'surah11_part6.mp3.json',
 'surah26_part1.mp3.json',
 'surah108_part1.mp3.json',
 'surah28_part6.mp3.json',
 'surah9_part13.mp3.json',
 'surah83_part2.mp3.json',
 'surah67_part1.mp3.json',
 'surah2_part8.mp3.json',
 'surah52_part2.mp3.json',
 'surah42_part1.mp3.json',
 'surah21_part3.mp3.json',
 'surah51_part2.mp3.json',
 'surah36_part2.mp3.json',
 'surah39_part6.mp3.json',
 'surah35_part2.mp3.json',
 'surah14_part5.mp3.json',
 'surah70_part1.mp3.json',
 'surah55_part3.mp3.json',
 'surah4_part5.mp3.json',
 'surah57_part1.mp3.json',
 'surah57_part2.mp3.json',
 'surah112_part1.mp3.json',
 'surah31_part1.mp3.json',
 'surah73_part1.mp3.json',
 'surah38_part3.mp3.json',
 'surah20_part3.mp3.json',
 'surah9_part14.mp3.json',
 'surah12_part6.mp3.json',
 'surah28_part1.mp3.json',
 'surah7_part3.mp3.json',
 'surah6_part6.mp3.json',
 's

In [6]:
# Extract correct maqams (y_correct)
y_correct = []
for file in sampled_labels:
    json_file_path = os.getcwd() + '/labels/' + file
    with open(json_file_path, "r") as json_file:
        label_data = json.load(json_file)
        maqam = label_data["maqam"].strip("[]'")  # Clean brackets and quotes
        y_correct.append(maqam)
    print(file, maqam)

surah22_part1.mp3.json كرد
surah56_part1.mp3.json بيات
surah11_part7.mp3.json راست
surah19_part2.mp3.json حجاز
surah72_part1.mp3.json سيكاه
surah96_part1.mp3.json نهاوند
surah11_part6.mp3.json نهاوند
surah26_part1.mp3.json صبا
surah108_part1.mp3.json بيات
surah28_part6.mp3.json راست
surah9_part13.mp3.json حجاز
surah83_part2.mp3.json بيات
surah67_part1.mp3.json راست
surah2_part8.mp3.json بيات
surah52_part2.mp3.json نهاوند
surah42_part1.mp3.json راست
surah21_part3.mp3.json بيات
surah51_part2.mp3.json نهاوند
surah36_part2.mp3.json حجاز
surah39_part6.mp3.json بيات
surah35_part2.mp3.json نهاوند
surah14_part5.mp3.json راست
surah70_part1.mp3.json حجاز
surah55_part3.mp3.json نهاوند
surah4_part5.mp3.json بيات
surah57_part1.mp3.json بيات
surah57_part2.mp3.json حجاز
surah112_part1.mp3.json بيات
surah31_part1.mp3.json بيات
surah73_part1.mp3.json بيات
surah38_part3.mp3.json نهاوند
surah20_part3.mp3.json حجاز
surah9_part14.mp3.json سيكاه
surah12_part6.mp3.json بيات
surah28_part1.mp3.json بيات
surah7

In [7]:
start = time.time()
y_pred = []

for file in sampled_files:
    file_path = os.getcwd() + '/data/' + file
    processor = AudioProcessor(file_path, compute_audio)
    summary = processor.process_mew()
    y_pred.append(summary)
    print(file, summary)
    
end = time.time()
print('seconds:', end - start)

MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.06869385 -0.07850574 -0.05781014 ...  0.24250892  0.29447985
  0.2300407 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.2316055   0.31838417  0.25933802 ... -0.06368868 -0.0943834
 -0.06278887]
this is self.computed: <class 'numpy.ndarray'>
[0.05998493 0.07130654 0.05892746 ... 0.14287366 0.09318151 0.04017318]
this is self.computed: <class 'numpy.ndarray'>
[-0.0379939  -0.04567074 -0.04013194 ... -0.01214032 -0.01513121
 -0.01245297]
this is self.computed: <class 'numpy.ndarray'>
[ 0.04138388  0.05153734  0.04513412 ... -0.06630065 -0.05578559
 -0.03570933]
this is self.computed: <class 'numpy.ndarray'>
[ 0.04054694  0.05737478  0.05747709 ... -0.17811525 -0.15517046
 -0.09588566]
this is self.computed: <class 'numpy.ndarray'>
[ 0.01197107  0.01503432  0.0134246  ... -0.00375071 -0.00317781
 -0.00210256]
this is self.computed: <class 'numpy.ndarray'>
[-0.04888628 -0.09537215 -0.11951074 ...  0.1180467   0.0792571

2025-03-04 08:47:31.009813: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/ubuntu/videos/myenv_new/lib/python3.7/site-packages/cv2/../../lib64:
2025-03-04 08:47:31.009874: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2025-03-04 08:47:31.009905: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-29-3): /proc/driver/nvidia/version does not exist
2025-03-04 08:47:31.010299: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appr

1/1 [==============================] - 0s 24ms/step
surah22_part1.mp3 Hejaz
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.13757636 -0.18514204 -0.160591   ...  0.04524165  0.0349715
  0.01935126]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00893346  0.0021103  -0.00857252 ...  0.10329661  0.15086915
  0.13065718]
this is self.computed: <class 'numpy.ndarray'>
[ 0.33846986  0.44450384  0.37117428 ... -0.1717076  -0.1986504
 -0.1570045 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.00480157  0.00212308 -0.03689855 ...  0.4104733   0.41894776
  0.29296473]
this is self.computed: <class 'numpy.ndarray'>
[0.14532736 0.21181011 0.20314853 ... 0.09587469 0.12157094 0.09811436]
this is self.computed: <class 'numpy.ndarray'>
[ 0.          0.          0.         ... -0.12595947 -0.06904027
 -0.01457455]
this is self.computed: <class 'numpy.ndarray'>
[0.27997783 0.32558    0.26311183 ... 0.26200563 0.3577771  0.30110392]
this is self.computed: <class 'numpy.ndarray'>
[ 0.10272491  0.13173434  0.10905176 ... -0.03545507 -0.04374279
 -0.03

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.04464155  0.03237425 -0.03334528 ... -0.10302866 -0.1682517
 -0.15238857]
this is self.computed: <class 'numpy.ndarray'>
[-0.17073676 -0.2447662  -0.25040534 ...  0.04865956  0.05590653
  0.04386342]
this is self.computed: <class 'numpy.ndarray'>
[-0.00768191 -0.00444376  0.00219675 ...  0.03595692  0.04311474
  0.04125319]
this is self.computed: <class 'numpy.ndarray'>
[ 0.14624724  0.17597097  0.15660092 ... -0.00698544 -0.07607094
 -0.09536257]
this is self.computed: <class 'numpy.ndarray'>
[-0.01435907 -0.01960232 -0.01944518 ...  0.13109319  0.16524297
  0.13098684]
this is self.computed: <class 'numpy.ndarray'>
[-0.10651082 -0.19558933 -0.2595724  ... -0.00081164 -0.0063208
 -0.00814616]
1/1 [==============================] - 0s 25ms/step
surah11_part7.mp3 Hejaz
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.16946697 -0.18213713 -0.11906841 ... -0.41466314 -0.5424502
 -0.45678335]
this is self.computed: <class 'numpy.ndarray'>
[-0.44995713 -0.61911666 -0.5796511  ... -0.10597154 -0.06501044
 -0.02672441]
this is self.computed: <class 'numpy.ndarray'>
[-0.01398663 -0.01866381 -0.01776606 ... -0.3427667  -0.3475444
 -0.24498373]
this is self.computed: <class 'numpy.ndarray'>
[ 0.28098696  0.37538886  0.2958266  ... -0.11254109 -0.18449163
 -0.1669089 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.1979671  -0.28912097 -0.29955196 ...  0.28104663  0.31116408
  0.23366195]
this is self.computed: <class 'numpy.ndarray'>
[-0.23879002 -0.307146   -0.25165316 ... -0.18414284 -0.1923391
 -0.14177015]
this is self.computed: <class 'numpy.ndarray'>
[0.01697909 0.0549751  0.09426939 ... 0.43673646 0.486921   0.37334436]
this is self.computed: <class 'numpy.ndarray'>
[-0.13358282 -0.14314933 -0.11245537 ...  0.07004747  0.031172
  

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.02603712  0.03749991  0.03035603 ... -0.07413161 -0.03978667
 -0.00010348]
this is self.computed: <class 'numpy.ndarray'>
[-0.00130992 -0.02674989 -0.04156106 ...  0.36598718  0.41553926
  0.3197195 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.00661942  0.01247435  0.04718939 ... -0.0104488  -0.01047738
 -0.00760609]
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>
[ 0.14051723  0.16679934  0.13144396 ... -0.00293562  0.0143669
  0.01916875]
this is self.computed: <class 'numpy.ndarray'>
[-0.15018456 -0.16341886 -0.09982154 ... -0.44975933 -0.492382
 -0.39503288]
this is self.computed: <class 'numpy.ndarray'>
[-0.00657526 -0.00805077 -0.00719225 ...  0.05555641  0.07065044
  0.05898801]
this is self.computed: <class 'numpy.ndarray'>
[0.3403017  0.436741   0.3411575  ... 0.02991692 0.04143923 0.03500278]
this is self.computed: <class 'numpy.ndar

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>
[0.08041478 0.08960073 0.06168255 ... 0.         0.         0.        ]
this is self.computed: <class 'numpy.ndarray'>
[-0.01929433  0.00472192  0.04478156 ...  0.10549787  0.11283387
  0.08250884]
this is self.computed: <class 'numpy.ndarray'>
[ 0.          0.          0.         ... -0.09440796 -0.0630227
 -0.03214771]
this is self.computed: <class 'numpy.ndarray'>
[0.07413273 0.08082719 0.07512518 ... 0.11519271 0.1291744  0.09657186]
1/1 [==============================] - 0s 24ms/step
surah96_part1.mp3 Bayat
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.1022726  -0.12906893 -0.11560134 ... -0.08871391 -0.10206708
 -0.07742991]
this is self.computed: <class 'numpy.ndarray'>
[-0.073425   -0.08714553 -0.07407211 ... -0.00949961 -0.01220926
 -0.01005124]
this is self.computed: <class 'numpy.ndarray'>
[ 0.46696424  0.6064865   0.48978245 ... -0.13154101 -0.14338994
 -0.10798636]
this is self.computed: <class 'numpy.ndarray'>
[-0.0945226  -0.15630442 -0.17327338 ... -0.38094282 -0.39554513
 -0.27933246]
this is self.computed: <class 'numpy.ndarray'>
[-0.00997538 -0.0135496  -0.01351652 ...  0.33964592  0.42470163
  0.34326798]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00385498  0.00513862  0.00418286 ...  0.1326287   0.04423866
 -0.02987934]
this is self.computed: <class 'numpy.ndarray'>
[-0.29101652 -0.30923408 -0.19738264 ...  0.45758396  0.53549564
  0.4119739 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.36789823  0.5115145   0.44152948 ... -0.02671139 -0

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.06268859  0.08622031  0.0911518  ... -0.22179656 -0.20635788
 -0.13754222]
this is self.computed: <class 'numpy.ndarray'>
[-0.11440004 -0.12768444 -0.06038905 ... -0.19314371 -0.28797764
 -0.25136927]
this is self.computed: <class 'numpy.ndarray'>
[0.28588605 0.4322855  0.38878182 ... 0.18478695 0.22755095 0.17696905]
this is self.computed: <class 'numpy.ndarray'>
[-0.12837592 -0.20729445 -0.21534622 ...  0.05109431  0.06421116
  0.05718115]
this is self.computed: <class 'numpy.ndarray'>
[-0.13603519 -0.16209278 -0.15034378 ... -0.01689876 -0.02396175
 -0.02028953]
this is self.computed: <class 'numpy.ndarray'>
[ 0.22694053  0.31487685  0.312227   ... -0.23770653 -0.29060864
 -0.2421434 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.25533724 -0.37175506 -0.42406738 ...  0.11610703  0.10957922
  0.07605173]
this is self.computed: <class 'numpy.ndarray'>
[-0.21236986 -0.27277514 -0.25977522 ...  0.1072627   0.114192

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-1.0209904e-02 -1.3667893e-02 -1.1891747e-02 ... -3.9247563e-05
 -1.0461095e-03 -1.4206263e-03]
this is self.computed: <class 'numpy.ndarray'>
[ 0.          0.          0.         ... -0.01628248 -0.01779297
 -0.01362148]
1/1 [==============================] - 0s 25ms/step
surah108_part1.mp3 Bayat
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.02084218  0.02559822  0.01950153 ... -0.26234913 -0.3534273
 -0.29641312]
this is self.computed: <class 'numpy.ndarray'>
[-0.33898115 -0.46490374 -0.4629697  ...  0.01268268  0.01790302
  0.01577155]
this is self.computed: <class 'numpy.ndarray'>
[-0.05658241 -0.07487439 -0.06615841 ...  0.36125192  0.4161222
  0.31975114]
this is self.computed: <class 'numpy.ndarray'>
[0.25730544 0.32884258 0.3065158  ... 0.0037708  0.01360233 0.01603259]
this is self.computed: <class 'numpy.ndarray'>
[-0.22483149 -0.31791693 -0.30717397 ...  0.17202389  0.16148978
  0.11001764]
this is self.computed: <class 'numpy.ndarray'>
[0.32170504 0.40987796 0.3874731  ... 0.         0.         0.        ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.01663172  0.02244336  0.02224056 ... -0.13338435 -0.17844518
 -0.15274018]
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.00041528 -0.00047754 -0.00033803 ... -0.1003259  -0.10375572
 -0.07610327]
this is self.computed: <class 'numpy.ndarray'>
[-0.13087988 -0.17084701 -0.12475334 ...  0.02107394  0.01580506
  0.00867486]
this is self.computed: <class 'numpy.ndarray'>
[-0.15503412 -0.21371983 -0.16563238 ... -0.14620015 -0.16899645
 -0.1318897 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00391652  0.00097688 -0.00416709 ... -0.0009609  -0.00097452
 -0.00069131]
1/1 [==============================] - 0s 26ms/step
surah9_part13.mp3 Ajam
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.03946983 -0.07242177 -0.09793064 ...  0.12998942  0.13216983
  0.09519139]
this is self.computed: <class 'numpy.ndarray'>
[ 0.16419953  0.24650681  0.21098813 ...  0.0069126  -0.00780391
 -0.01699217]
this is self.computed: <class 'numpy.ndarray'>
[0.09000707 0.10090378 0.06890361 ... 0.14388537 0.15434064 0.11808237]
1/1 [==============================] - 0s 25ms/step
surah83_part2.mp3 Ajam
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.05491371 -0.06916804 -0.05707725 ...  0.26214957  0.35536444
  0.31558776]
this is self.computed: <class 'numpy.ndarray'>
[0.31551975 0.4607588  0.4016056  ... 0.07280457 0.07850903 0.05988132]
this is self.computed: <class 'numpy.ndarray'>
[0.1256817  0.1586785  0.12788266 ... 0.47268632 0.5522973  0.42057166]
this is self.computed: <class 'numpy.ndarray'>
[-0.01812354 -0.02559193 -0.02567644 ...  0.          0.
  0.        ]
this is self.computed: <class 'numpy.ndarray'>
[-0.00887518 -0.01046823 -0.00274212 ... -0.04786814 -0.05843511
 -0.04898699]
this is self.computed: <class 'numpy.ndarray'>
[ 0.23505265  0.33619127  0.32084244 ... -0.07751551 -0.09781574
 -0.07880786]
this is self.computed: <class 'numpy.ndarray'>
[0.41983333 0.5471649  0.45513546 ... 0.03256062 0.03581723 0.02750043]
this is self.computed: <class 'numpy.ndarray'>
[0.05748455 0.06331475 0.05240721 ... 0.11935399 0.14174214 0.11275387]
this is self

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.08555376 -0.10860553 -0.09400996 ... -0.17776349 -0.19474068
 -0.14537269]
this is self.computed: <class 'numpy.ndarray'>
[-0.01209445 -0.01873068 -0.01830474 ... -0.10982399 -0.11687548
 -0.08771275]
this is self.computed: <class 'numpy.ndarray'>
[-0.14283146 -0.16084379 -0.08832495 ... -0.12330124 -0.13492268
 -0.10295567]
1/1 [==============================] - 0s 25ms/step
surah2_part8.mp3 Hejaz
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.28072658 0.36379173 0.31390405 ... 0.02414966 0.01396294 0.00468172]
this is self.computed: <class 'numpy.ndarray'>
[-0.00630225 -0.01440404 -0.02417523 ...  0.0861358   0.09240793
  0.0690318 ]
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>
[0.03381455 0.03658424 0.02702602 ... 0.35988098 0.42281392 0.32491356]
this is self.computed: <class 'numpy.ndarray'>
[-0.12315462 -0.15238942 -0.12334564 ...  0.31557912  0.36297175
  0.2804867 ]
this is self.computed: <class 'numpy.ndarray'>
[0.05651995 0.07923905 0.07873072 ... 0.32022494 0.33959073 0.24683675]
this is self.computed: <class 'numpy.ndarray'>
[ 0.21124643  0.28459948  0.27650917 ... -0.12483527 -0.15359068
 -0.12184751]
this is self.computed: <class 'numpy.ndarray'>
[-0.06311677 -0.0788058  -0.0657249  ...  0.          0.
  0.        ]
this is self.computed: <class 'numpy.ndarray'>
[0.28335688 0

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.00216065 -0.00362369 -0.00534846 ...  0.44692406  0.57933307
  0.47595817]
this is self.computed: <class 'numpy.ndarray'>
[ 5.1553601e-01  7.2769934e-01  6.1311030e-01 ... -2.0197483e-03
 -1.0174066e-03 -1.4837133e-04]
this is self.computed: <class 'numpy.ndarray'>
[-0.40654027 -0.5136803  -0.43023145 ... -0.16914594 -0.19495693
 -0.14662047]
this is self.computed: <class 'numpy.ndarray'>
[ 0.3198893   0.41983873  0.35865766 ... -0.00918556 -0.01448967
 -0.01210169]
this is self.computed: <class 'numpy.ndarray'>
[-0.05152501 -0.07525701 -0.07925354 ...  0.0004097  -0.00076385
 -0.00118155]
this is self.computed: <class 'numpy.ndarray'>
[0.0987293  0.10421694 0.08440435 ... 0.13007504 0.13226075 0.09130599]
this is self.computed: <class 'numpy.ndarray'>
[-0.12424714 -0.15261066 -0.12303702 ... -0.00313453 -0.00362097
 -0.00314306]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00044869  0.00125632  0.00236051 ... -0.

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.0024211  -0.00656886 -0.01053433 ... -0.28527135 -0.35169142
 -0.27626973]
this is self.computed: <class 'numpy.ndarray'>
[-0.27082217 -0.38745928 -0.36471128 ...  0.          0.
  0.        ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.01399665  0.01805034  0.01643236 ...  0.00718953  0.00061376
 -0.00139162]
this is self.computed: <class 'numpy.ndarray'>
[0.04618796 0.07051923 0.07495917 ... 0.06223663 0.07601298 0.06047242]
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>
[0.13486764 0.1839979  0.12540773 ... 0.0533964  0.06206682 0.04835211]
this is self.computed: <class 'numpy.ndarray'>
[0.05352807 0.07192947 0.07189193 ... 0.01803263 0.02020618 0.01573622]
1/1 [==============================] - 0s 29ms/step
surah21_part3.mp3 Seekah
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.15774806 -0.18863815 -0.18019746 ...  0.5070808   0.60686344
  0.47260717]
this is self.computed: <class 'numpy.ndarray'>
[0.4311282  0.49005353 0.42639074 ... 0.01263124 0.00828246 0.00370102]
this is self.computed: <class 'numpy.ndarray'>
[-0.49571764 -0.6630827  -0.61190546 ... -0.3399148  -0.37669498
 -0.29102385]
this is self.computed: <class 'numpy.ndarray'>
[-0.03264076 -0.04788456 -0.04973143 ... -0.1557142  -0.18834159
 -0.15289348]
this is self.computed: <class 'numpy.ndarray'>
[-0.0830054  -0.10558175 -0.10421436 ... -0.07180074 -0.0807647
 -0.06155416]
this is self.computed: <class 'numpy.ndarray'>
[-0.27676946 -0.36886263 -0.28637704 ... -0.06608444 -0.0929704
 -0.08437435]
this is self.computed: <class 'numpy.ndarray'>
[0.00448106 0.00742248 0.0058953  ... 0.01018541 0.00642848 0.00312457]
this is self.computed: <class 'numpy.ndarray'>
[-0.07553505 -0.12022091 -0.13619986 ... -0.19881418 -0.22985005
 -0.18

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.07946617 -0.10845972 -0.10702544 ...  0.0515666   0.17076132
  0.18533014]
this is self.computed: <class 'numpy.ndarray'>
[-0.08889498 -0.12938806 -0.13717999 ...  0.16708043  0.15324013
  0.09044071]
this is self.computed: <class 'numpy.ndarray'>
[ 0.05791661  0.06744832  0.04720954 ... -0.07716697 -0.0950478
 -0.07823711]
this is self.computed: <class 'numpy.ndarray'>
[-0.41809046 -0.5720186  -0.50628173 ... -0.0268954  -0.03034101
 -0.02245403]
this is self.computed: <class 'numpy.ndarray'>
[ 0.01235921  0.01870112  0.01808759 ... -0.40303683 -0.4994972
 -0.41169113]
this is self.computed: <class 'numpy.ndarray'>
[-0.01902586 -0.02577364 -0.02463078 ...  0.06043933  0.06982708
  0.05607546]
1/1 [==============================] - 0s 25ms/step
surah36_part2.mp3 Hejaz
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>
[ 0.2587935   0.32811838  0.26839167 ... -0.03260519 -0.03917493
 -0.0324755 ]
this is self.computed: <class 'numpy.ndarray'>
[0.00061442 0.00083302 0.00091652 ... 0.36817983 0.40022182 0.31124464]
this is self.computed: <class 'numpy.ndarray'>
[-0.03649445 -0.03923198 -0.03811627 ...  0.          0.
  0.        ]
1/1 [==============================] - 0s 26ms/step
surah39_part6.mp3 Bayat
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip19.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip20.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip21.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip22.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip23.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip24.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.15116903 -0.17777368 -0.140342   ...  0.00352056 -0.00432204
 -0.00767543]
this is self.computed: <class 'numpy.ndarray'>
[-0.01319113 -0.02196028 -0.02855336 ... -0.13409005 -0.10371359
 -0.05808941]
this is self.computed: <class 'numpy.ndarray'>
[0.10023612 0.1344769  0.13125809 ... 0.15642473 0.22938986 0.19728076]
this is self.computed: <class 'numpy.ndarray'>
[-0.13406967 -0.19372675 -0.17135946 ... -0.14433327 -0.173928
 -0.14281811]
this is self.computed: <class 'numpy.ndarray'>
[0.07078676 0.08821898 0.06380214 ... 0.34654397 0.41505033 0.3256248 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.03099426 -0.04590447 -0.04561104 ... -0.27120018 -0.26139605
 -0.17782235]
this is self.computed: <class 'numpy.ndarray'>
[-0.26216877 -0.3345545  -0.2567039  ...  0.47142276  0.5815835
  0.46268308]
this is self.computed: <class 'numpy.ndarray'>
[-0.16067463 -0.21021372 -0.19165623 ... -0.33257034 -0.36566234
 -0.282

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.05227183 -0.06681203 -0.06193287 ...  0.06481458  0.07822132
  0.05794123]
this is self.computed: <class 'numpy.ndarray'>
[ 0.12668753  0.17032877  0.15390632 ... -0.06061162 -0.07328475
 -0.05910347]
this is self.computed: <class 'numpy.ndarray'>
[ 0.09565931  0.11903495  0.11373353 ... -0.13949701 -0.04579748
  0.00393416]
this is self.computed: <class 'numpy.ndarray'>
[-0.00653664 -0.01046147 -0.00882012 ...  0.12038103  0.13667881
  0.10429537]
this is self.computed: <class 'numpy.ndarray'>
[0.01304979 0.03302443 0.04399814 ... 0.18818545 0.20080557 0.15011865]
1/1 [==============================] - 0s 25ms/step
surah14_part5.mp3 Bayat
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.08100526 -0.0838128  -0.06855516 ... -0.18976119 -0.20408866
 -0.15736881]
this is self.computed: <class 'numpy.ndarray'>
[-0.15630402 -0.2450986  -0.28473318 ... -0.28879595 -0.29655993
 -0.20926437]
this is self.computed: <class 'numpy.ndarray'>
[ 0.06908748  0.12076275  0.15312171 ... -0.04850572 -0.0472528
 -0.02914104]
this is self.computed: <class 'numpy.ndarray'>
[-0.14300144 -0.19072485 -0.17394179 ... -0.16172685 -0.15789264
 -0.11007899]
this is self.computed: <class 'numpy.ndarray'>
[ 0.07818559  0.10597225  0.09470256 ... -0.31733194 -0.35174143
 -0.26387706]
this is self.computed: <class 'numpy.ndarray'>
[-0.02871086 -0.05433904 -0.08150066 ...  0.          0.
  0.        ]
this is self.computed: <class 'numpy.ndarray'>
[-0.20739323 -0.27551806 -0.25955465 ... -0.15556821 -0.14982492
 -0.10201895]
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.nda

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.04981731  0.00788352  0.08943961 ...  0.27620775  0.30517265
  0.23682316]
this is self.computed: <class 'numpy.ndarray'>
[0.22278276 0.26946104 0.20370667 ... 0.07450986 0.0925889  0.07394677]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00231305  0.0012835  -0.00089127 ...  0.          0.
  0.        ]
this is self.computed: <class 'numpy.ndarray'>
[-0.24457751 -0.3138652  -0.2903896  ... -0.4064624  -0.32364732
 -0.17574944]
this is self.computed: <class 'numpy.ndarray'>
[ 0.08738272  0.13365927  0.17416076 ... -0.247154   -0.27875826
 -0.20724364]
this is self.computed: <class 'numpy.ndarray'>
[ 0.08329629  0.10929295  0.09687361 ... -0.1223623  -0.10269327
 -0.05997701]
this is self.computed: <class 'numpy.ndarray'>
[-0.28910393 -0.44397306 -0.47265416 ...  0.10043301  0.10951671
  0.07964695]
this is self.computed: <class 'numpy.ndarray'>
[-0.1172065  -0.17840044 -0.18848574 ...  0.0056042   0.00536448
  0.0

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.0766805  -0.08630688 -0.07160464 ... -0.18687885 -0.18973866
 -0.14201525]
this is self.computed: <class 'numpy.ndarray'>
[-0.12415805 -0.1391485  -0.1281979  ... -0.11041791 -0.18304251
 -0.16290268]
this is self.computed: <class 'numpy.ndarray'>
[ 0.03345142  0.0427546   0.03765392 ... -0.00760692 -0.01112379
 -0.0101174 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.17691287  0.23421907  0.2042531  ... -0.1285264  -0.13612701
 -0.10008062]
this is self.computed: <class 'numpy.ndarray'>
[-0.08180825 -0.11752722 -0.12890685 ...  0.10291336  0.11077181
  0.08263168]
this is self.computed: <class 'numpy.ndarray'>
[-0.01023845 -0.01120726 -0.00728605 ...  0.06832227  0.08190601
  0.0740326 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.223461   -0.27614707 -0.28496513 ... -0.09190342 -0.10421215
 -0.08287808]
this is self.computed: <class 'numpy.ndarray'>
[ 0.15789771  0.30354533  0.38878417 ... -0.33088169 -0

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.1979618  0.25063467 0.25550026 ... 0.02547002 0.03596399 0.02014151]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00688391 -0.02682881 -0.07829267 ...  0.18188143  0.22473128
  0.16674434]
this is self.computed: <class 'numpy.ndarray'>
[0.01044988 0.01451008 0.0136588  ... 0.14966634 0.20282042 0.17495947]
this is self.computed: <class 'numpy.ndarray'>
[-0.034224   -0.04378219 -0.04182013 ... -0.02960593 -0.09897605
 -0.09777667]
this is self.computed: <class 'numpy.ndarray'>
[0.1419946  0.17724006 0.18173587 ... 0.04555322 0.05654572 0.04789658]
this is self.computed: <class 'numpy.ndarray'>
[ 0.          0.          0.         ... -0.03734217 -0.03902135
 -0.0291765 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.09641571 -0.14560732 -0.15506427 ...  0.01158618  0.01312866
  0.01026152]
this is self.computed: <class 'numpy.ndarray'>
[ 0.04842035  0.07875693  0.07935271 ... -0.01398922 -0.01700389
 -0.0134653

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.04189943 -0.05618913 -0.05446091 ... -0.00046333 -0.00258606
 -0.00315024]
this is self.computed: <class 'numpy.ndarray'>
[-0.13014764 -0.19435853 -0.20003203 ... -0.02153262 -0.05059102
 -0.04755918]
this is self.computed: <class 'numpy.ndarray'>
[0.40766305 0.42590147 0.28967613 ... 0.10052676 0.13116947 0.10624504]
this is self.computed: <class 'numpy.ndarray'>
[-0.25197574 -0.34843066 -0.3524238  ...  0.576344    0.61671656
  0.4468724 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.10883738  0.14195636  0.12409174 ... -0.05768611 -0.1141022
 -0.11020672]
1/1 [==============================] - 0s 25ms/step
surah57_part2.mp3 Hejaz
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ... -2.2267690e-05
 -1.1191866e-04 -1.7085206e-04]
1/1 [==============================] - 0s 212ms/step
surah112_part1.mp3 Bayat
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.03717003  0.0922624   0.10490407 ... -0.16452222 -0.17857085
 -0.13245338]
this is self.computed: <class 'numpy.ndarray'>
[-0.14139295 -0.17995104 -0.14425576 ...  0.02014463  0.01740544
  0.01065061]
this is self.computed: <class 'numpy.ndarray'>
[0.22112313 0.27772337 0.23327276 ... 0.08357001 0.07398197 0.03315401]
this is self.computed: <class 'numpy.ndarray'>
[ 0.06929609  0.09434809  0.08465609 ... -0.29621997 -0.37964833
 -0.30107573]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00167613 -0.00165316 -0.00768764 ...  0.00330817  0.0021036
  0.00118726]
this is self.computed: <class 'numpy.ndarray'>
[0.         0.         0.         ... 0.11582602 0.12868547 0.09621204]
this is self.computed: <class 'numpy.ndarray'>
[-0.30670035 -0.35771608 -0.3136981  ...  0.2900723   0.31637567
  0.23507775]
1/1 [==============================] - 0s 28ms/step
surah31_part1.mp3 Bayat
MoviePy - Writing audio in temporary/clip

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.12974341  0.15849118  0.10704659 ... -0.02486111 -0.02631339
 -0.01871437]
this is self.computed: <class 'numpy.ndarray'>
[-0.01335531 -0.01636233 -0.01396936 ...  0.01667144  0.00640595
 -0.00072087]
this is self.computed: <class 'numpy.ndarray'>
[0.2246747  0.2735061  0.25902525 ... 0.         0.         0.        ]
this is self.computed: <class 'numpy.ndarray'>
[-0.04812351 -0.07775263 -0.09644148 ...  0.25848395  0.2643044
  0.18837142]
this is self.computed: <class 'numpy.ndarray'>
[-0.01647902 -0.01934864 -0.01192358 ... -0.28644928 -0.3095073
 -0.22552612]
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>
[-0.02886678 -0.03704912 -0.03563701 ... -0.51881266 -0.59489936
 -0.4566249 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.          0.          0.         ... -0.02878834 -0.02798919
 -0.01940543]
this is self.computed: <class 'numpy.nda

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.00965889 0.02086276 0.02814852 ... 0.08767573 0.10965788 0.09122093]
this is self.computed: <class 'numpy.ndarray'>
[0.09405591 0.13374166 0.1449387  ... 0.25996947 0.26434544 0.17986974]
this is self.computed: <class 'numpy.ndarray'>
[ 0.33632714  0.40759975  0.3542269  ... -0.02602217 -0.01384258
 -0.00281104]
this is self.computed: <class 'numpy.ndarray'>
[ 0.13487764  0.20011121  0.21829419 ... -0.018859   -0.01931578
 -0.01363068]
this is self.computed: <class 'numpy.ndarray'>
[ 0.13289359  0.14066261  0.07521365 ... -0.46039063 -0.45226717
 -0.2999766 ]
this is self.computed: <class 'numpy.ndarray'>
[0.42787603 0.5364883  0.5472045  ... 0.04826272 0.08270878 0.07308806]
this is self.computed: <class 'numpy.ndarray'>
[0.26909176 0.35956597 0.3046335  ... 0.         0.         0.        ]
this is self.computed: <class 'numpy.ndarray'>
[-0.01184549 -0.01446189 -0.01444908 ...  0.38259625  0.42371866
  0.3325426 ]
this

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.18499762  0.22202857  0.22160146 ... -0.2174778  -0.25106353
 -0.19894555]
this is self.computed: <class 'numpy.ndarray'>
[-0.19263932 -0.23458752 -0.19589058 ... -0.32634422 -0.42382824
 -0.36576372]
this is self.computed: <class 'numpy.ndarray'>
[-0.24463704 -0.32998842 -0.26939258 ... -0.15919182 -0.13567263
 -0.07849276]
this is self.computed: <class 'numpy.ndarray'>
[-0.20714268 -0.2236317  -0.13259794 ...  0.19097823  0.25156617
  0.20511888]
this is self.computed: <class 'numpy.ndarray'>
[-0.24369538 -0.33486575 -0.30829236 ...  0.39769453  0.4617107
  0.35724372]
this is self.computed: <class 'numpy.ndarray'>
[-0.04362585 -0.05546829 -0.03032029 ...  0.35601306  0.43661678
  0.3492882 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.38701057 -0.5136438  -0.4568398  ... -0.05316941 -0.09594834
 -0.07921235]
this is self.computed: <class 'numpy.ndarray'>
[ 0.38308376  0.5056331   0.4646835  ... -0.00449455 -0.

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.14166641 -0.20635456 -0.21106803 ...  0.23508483  0.24986912
  0.18564242]
this is self.computed: <class 'numpy.ndarray'>
[0.1487814  0.19169226 0.15382826 ... 0.06848245 0.04106067 0.01591777]
this is self.computed: <class 'numpy.ndarray'>
[ 0.03633259  0.03905284  0.0254262  ... -0.10719552 -0.0288968
 -0.00386062]
this is self.computed: <class 'numpy.ndarray'>
[ 0.07897399  0.09965353  0.07395925 ... -0.15011442 -0.1946118
 -0.15844046]
this is self.computed: <class 'numpy.ndarray'>
[ 4.9750051e-03 -2.4729595e-04 -6.0208882e-03 ... -3.3272272e-01
 -4.3060583e-01 -3.7449461e-01]
this is self.computed: <class 'numpy.ndarray'>
[0.03933591 0.09874229 0.14108208 ... 0.09046352 0.07528497 0.04531976]
this is self.computed: <class 'numpy.ndarray'>
[-0.00692283 -0.02738854 -0.04962437 ...  0.3291831   0.3345562
  0.23973924]
this is self.computed: <class 'numpy.ndarray'>
[ 0.01775464  0.0067737  -0.01556192 ...  0.48271197  

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip19.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.00596678 -0.00863668 -0.00950141 ...  0.22371908  0.19888912
  0.12508185]
this is self.computed: <class 'numpy.ndarray'>
[ 0.08807972  0.07207118  0.0127211  ... -0.66375005 -0.77810085
 -0.6147822 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.12654436 -0.154602   -0.16555075 ... -0.16270031 -0.15944391
 -0.1138615 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.10399073 -0.12694457 -0.08257515 ...  0.          0.
  0.        ]
this is self.computed: <class 'numpy.ndarray'>
[-0.0104988  -0.01342008 -0.01194509 ... -0.09582619 -0.10836518
 -0.0789433 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.24270758  0.27631697  0.22327922 ... -0.00523542 -0.00669325
 -0.00566852]
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>
[-3.2190498e-02 -1.5352100e-02  1.2167543e-04 ... -3.3429271e-01
 -3.2469863e-01 -2.3092549e-01]
this is self.computed

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip19.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip20.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.3909347  -0.46065146 -0.40592408 ... -0.41370487 -0.48070157
 -0.3720315 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.36396617 -0.49517962 -0.4686504  ...  0.08923035  0.01223723
 -0.03932428]
this is self.computed: <class 'numpy.ndarray'>
[ 0.3988521   0.4920286   0.40259722 ... -0.10259579 -0.11201857
 -0.08724375]
this is self.computed: <class 'numpy.ndarray'>
[-0.00315045  0.00104189  0.00734258 ...  0.00878556  0.00045538
 -0.00583461]
this is self.computed: <class 'numpy.ndarray'>
[-0.25961414 -0.2717986  -0.10583954 ... -0.05561526 -0.08413832
 -0.07574998]
this is self.computed: <class 'numpy.ndarray'>
[-0.5870038  -0.7145275  -0.55259013 ... -0.5665053  -0.59220266
 -0.42052412]
this is self.computed: <class 'numpy.ndarray'>
[0.41922545 0.4945567  0.32606515 ... 0.00950338 0.0145372  0.01339176]
this is self.computed: <class 'numpy.ndarray'>
[-0.0191778  -0.03600645 -0.05476949 ...  0.5758967   0.647206

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.08972329  0.15745446  0.20117666 ... -0.17646351 -0.23896068
 -0.19754982]
this is self.computed: <class 'numpy.ndarray'>
[ 0.01638934  0.02242793  0.01497477 ... -0.0249156   0.02326879
  0.05169423]
this is self.computed: <class 'numpy.ndarray'>
[-0.21126616 -0.2558145  -0.23312593 ... -0.01966849 -0.02341949
 -0.01889781]
1/1 [==============================] - 0s 25ms/step
surah7_part3.mp3 Hejaz
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.05666019 0.06740685 0.0677767  ... 0.14666028 0.1705585  0.13111776]
this is self.computed: <class 'numpy.ndarray'>
[ 0.12899563  0.15788427  0.13344234 ... -0.10445395 -0.00889525
  0.03623352]
this is self.computed: <class 'numpy.ndarray'>
[0.00564883 0.00307348 0.00069068 ... 0.43041158 0.45391196 0.34508532]
this is self.computed: <class 'numpy.ndarray'>
[0.16085404 0.20042656 0.15485123 ... 0.0294956  0.04915924 0.04416388]
this is self.computed: <class 'numpy.ndarray'>
[-0.40331382 -0.4860197  -0.3975489  ... -0.02129302 -0.0217848
 -0.01333959]
this is self.computed: <class 'numpy.ndarray'>
[ 0.3273121   0.37581965  0.33761346 ... -0.4833774  -0.5251585
 -0.39267647]
this is self.computed: <class 'numpy.ndarray'>
[0.07775282 0.09471667 0.06294778 ... 0.5840054  0.69215375 0.527444  ]
this is self.computed: <class 'numpy.ndarray'>
[-0.37485558 -0.40501523 -0.2520957  ...  0.34853613  0.37592512
  0.28647295]
this i

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip19.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip20.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip21.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip22.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip23.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip24.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip25.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip26.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip27.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip28.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip29.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.03035118 -0.02373903  0.02653316 ...  0.19420624  0.23368075
  0.19104591]
this is self.computed: <class 'numpy.ndarray'>
[0.16520199 0.2449258  0.21592245 ... 0.18623799 0.20480627 0.15498133]
this is self.computed: <class 'numpy.ndarray'>
[-0.08559382 -0.11374276 -0.08923472 ... -0.3987969  -0.36903155
 -0.25008774]
this is self.computed: <class 'numpy.ndarray'>
[-0.20452619 -0.23415264 -0.17486897 ... -0.01674088 -0.02111924
 -0.01760143]
this is self.computed: <class 'numpy.ndarray'>
[0.10529479 0.14017542 0.1171101  ... 0.21443483 0.20698065 0.1427297 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.02178054 -0.02158967 -0.01370393 ...  0.22710486  0.26464444
  0.20448606]
this is self.computed: <class 'numpy.ndarray'>
[-0.09420604 -0.12761843 -0.12679656 ... -0.02181985 -0.0286567
 -0.02493164]
this is self.computed: <class 'numpy.ndarray'>
[0.00202901 0.00779    0.01409915 ... 0.07324147 0.09940875 0.04273178

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.10299049 0.11389498 0.05912136 ... 0.660502   0.73036426 0.5412054 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.48666224  0.5663952   0.41824847 ... -0.12106451 -0.13041069
 -0.09468108]
this is self.computed: <class 'numpy.ndarray'>
[0.24121839 0.30355424 0.24746747 ... 0.19399875 0.18527526 0.12143479]
this is self.computed: <class 'numpy.ndarray'>
[0.01915894 0.0271047  0.02499578 ... 0.0687452  0.07658993 0.05794349]
this is self.computed: <class 'numpy.ndarray'>
[-0.09215025 -0.10559337 -0.07143021 ... -0.01540763 -0.01544487
 -0.01050447]
this is self.computed: <class 'numpy.ndarray'>
[-0.20978105 -0.31387946 -0.272475   ...  0.05411889  0.05627077
  0.0390924 ]
this is self.computed: <class 'numpy.ndarray'>
[0.04736417 0.06013053 0.04861627 ... 0.2717709  0.31608075 0.24126014]
1/1 [==============================] - 0s 24ms/step
surah6_part5.mp3 Hejaz
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.25202608 -0.39812386 -0.4014681  ...  0.411116    0.46609357
  0.34697968]
this is self.computed: <class 'numpy.ndarray'>
[ 0.3957793   0.4830026   0.38785094 ... -0.00318634 -0.0031458
 -0.00203947]
this is self.computed: <class 'numpy.ndarray'>
[-0.02806161 -0.03452608 -0.03202365 ... -0.18387558 -0.2675801
 -0.22955894]
this is self.computed: <class 'numpy.ndarray'>
[0.2822563  0.38409984 0.31663054 ... 0.11269808 0.12979874 0.10185662]
this is self.computed: <class 'numpy.ndarray'>
[-0.14150506 -0.20609024 -0.15023941 ...  0.32283035  0.37720245
  0.28913292]
this is self.computed: <class 'numpy.ndarray'>
[ 0.09738684  0.12512937  0.11980905 ... -0.03061883 -0.03538145
 -0.02844176]
1/1 [==============================] - 0s 26ms/step
surah25_part6.mp3 Hejaz
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.03880732 -0.05334207 -0.05732796 ...  0.23436442  0.2562036
  0.18858178]
this is self.computed: <class 'numpy.ndarray'>
[0.18459882 0.21938197 0.17457388 ... 0.03078879 0.03771283 0.0298831 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.15431991 -0.22849262 -0.22637588 ... -0.03008726 -0.03922604
 -0.03398914]
this is self.computed: <class 'numpy.ndarray'>
[0.04326631 0.05163368 0.04134611 ... 0.30823553 0.33718044 0.2523062 ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.03041828  0.0408421   0.03413476 ... -0.00810003  0.03570854
  0.04243076]
this is self.computed: <class 'numpy.ndarray'>
[0.         0.         0.         ... 0.05457628 0.061434   0.04681233]
this is self.computed: <class 'numpy.ndarray'>
[ 0.25945306  0.31899568  0.24941391 ... -0.10852969 -0.15855959
 -0.13742098]
this is self.computed: <class 'numpy.ndarray'>
[0.06440911 0.11445192 0.14717008 ... 0.         0.         0.        ]
1/1 [

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip19.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip20.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip21.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip22.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip23.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip24.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip25.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip26.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip27.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.05950244 0.07561433 0.07195389 ... 0.27417928 0.32407498 0.2488939 ]
this is self.computed: <class 'numpy.ndarray'>
[0.23447387 0.283415   0.20961216 ... 0.03795207 0.05387136 0.04584856]
this is self.computed: <class 'numpy.ndarray'>
[ 0.15154126  0.20529738  0.19156483 ... -0.03746825 -0.0720185
 -0.06736249]
this is self.computed: <class 'numpy.ndarray'>
[-0.10498501 -0.09704672 -0.03386139 ...  0.11480254  0.15347952
  0.13199292]
this is self.computed: <class 'numpy.ndarray'>
[-0.25709778 -0.33577833 -0.293804   ... -0.10614385 -0.12616333
 -0.09889547]
this is self.computed: <class 'numpy.ndarray'>
[-0.00415277  0.00709638  0.02433583 ...  0.18482104  0.17509258
  0.12403277]
this is self.computed: <class 'numpy.ndarray'>
[-0.02790245 -0.0341538  -0.02940198 ...  0.05666504  0.07487587
  0.0613023 ]
this is self.computed: <class 'numpy.ndarray'>
[0.01464813 0.01560634 0.01239407 ... 0.0391168  0.02463209 0.00923109

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 0.03512178  0.03717303  0.0268909  ... -0.0090836  -0.00999
 -0.0076817 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.00702787 -0.00851106 -0.00711145 ...  0.          0.
  0.        ]
this is self.computed: <class 'numpy.ndarray'>
[0.19893786 0.264905   0.2153885  ... 0.05285221 0.0529897  0.03843258]
this is self.computed: <class 'numpy.ndarray'>
[-0.07257506 -0.09161922 -0.08335803 ... -0.1220381  -0.14014456
 -0.10771781]
this is self.computed: <class 'numpy.ndarray'>
[-0.00314814 -0.002942   -0.00208056 ... -0.08647226 -0.09651409
 -0.07569623]
this is self.computed: <class 'numpy.ndarray'>
[-0.10530525 -0.11804359 -0.10050862 ...  0.23680267  0.27415764
  0.21043041]
1/1 [==============================] - 0s 24ms/step
surah22_part4.mp3 Bayat
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[ 5.4068733e-03 -4.6708472e-03 -2.2357769e-02 ...  4.9185786e-05
  4.0854826e-05  2.9380444e-05]
this is self.computed: <class 'numpy.ndarray'>
[ 0.          0.          0.         ... -0.00858864 -0.046074
 -0.04430191]
1/1 [==============================] - 0s 24ms/step
surah113_part1.mp3 Bayat
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip19.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip20.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip21.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip22.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip23.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip24.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip25.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip26.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip27.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip28.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip29.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip30.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.1054996  -0.14443994 -0.13987973 ... -0.5314281  -0.63994694
 -0.49725372]
this is self.computed: <class 'numpy.ndarray'>
[-0.5228418  -0.6661419  -0.5512477  ...  0.08151098  0.07061002
  0.04095601]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00187861  0.02578301  0.0521977  ...  0.02032356  0.00088792
 -0.00953085]
this is self.computed: <class 'numpy.ndarray'>
[-0.02806766 -0.041732   -0.04115169 ...  0.2132484   0.26080993
  0.2032255 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.00197938 -0.01706253 -0.0324946  ...  0.08767337  0.10016362
  0.0776857 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.39592862 -0.52305853 -0.4518376  ...  0.30215266  0.33375332
  0.24554272]
this is self.computed: <class 'numpy.ndarray'>
[-0.11436057 -0.14695708 -0.13778198 ... -0.11530589 -0.14651924
 -0.12001183]
this is self.computed: <class 'numpy.ndarray'>
[ 0.00132359 -0.00093334 -0.01038485 ... -0.06680829 -0

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.0260744  0.04084839 0.04662644 ... 0.         0.         0.        ]
this is self.computed: <class 'numpy.ndarray'>
[0. 0. 0. ... 0. 0. 0.]
this is self.computed: <class 'numpy.ndarray'>
[0.4132431  0.61120975 0.5956619  ... 0.01198962 0.02498603 0.02495442]
this is self.computed: <class 'numpy.ndarray'>
[ 0.04941702  0.06605703  0.05482632 ... -0.10195842 -0.13813455
 -0.11428958]
this is self.computed: <class 'numpy.ndarray'>
[0.00396692 0.02032709 0.03663829 ... 0.06184332 0.06379905 0.05055416]
this is self.computed: <class 'numpy.ndarray'>
[-0.10752498 -0.14858471 -0.15073664 ...  0.12389082  0.2569254
  0.2584765 ]
1/1 [==============================] - 0s 27ms/step
surah32_part3.mp3 Bayat
MoviePy - Writing audio in temporary/clip1.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip19.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip20.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip21.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip22.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip23.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip24.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip25.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip26.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip27.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip28.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip29.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip30.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip31.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip32.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip33.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.09340742 0.13171123 0.12632303 ... 0.35481203 0.3967672  0.30463058]
this is self.computed: <class 'numpy.ndarray'>
[ 0.31643617  0.41031778  0.32830968 ... -0.06069022 -0.08192685
 -0.07104887]
this is self.computed: <class 'numpy.ndarray'>
[-0.49374652 -0.633701   -0.5412133  ...  0.07427063  0.02436494
  0.00624134]
this is self.computed: <class 'numpy.ndarray'>
[-0.06267196 -0.08066594 -0.06787227 ...  0.26713946  0.28788733
  0.21165253]
this is self.computed: <class 'numpy.ndarray'>
[-0.08727015 -0.11050674 -0.09538588 ...  0.18878356  0.19349901
  0.1448935 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.05746791 -0.08934053 -0.10182317 ... -0.30681306 -0.33506656
 -0.24641614]
this is self.computed: <class 'numpy.ndarray'>
[0.10053024 0.15219581 0.17944343 ... 0.54013306 0.64979523 0.5039103 ]
this is self.computed: <class 'numpy.ndarray'>
[0.08081853 0.06324592 0.00042659 ... 0.11820506 0.13358878 0.1034548

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[-0.26618174 -0.31725615 -0.25813854 ... -0.49660826 -0.560287
 -0.43703187]
this is self.computed: <class 'numpy.ndarray'>
[-0.3868178  -0.5266288  -0.51343316 ... -0.19728884 -0.29322824
 -0.24650817]
this is self.computed: <class 'numpy.ndarray'>
[0.04252681 0.05422285 0.04896512 ... 0.06926176 0.0830906  0.0680861 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.25361037 -0.31336495 -0.29423732 ...  0.          0.
  0.        ]
this is self.computed: <class 'numpy.ndarray'>
[ 0.2397449   0.29790568  0.2505992  ... -0.31632483 -0.3531047
 -0.27294263]
this is self.computed: <class 'numpy.ndarray'>
[ 0.07187451  0.0494565  -0.01235424 ...  0.01054151  0.01059338
  0.00768571]
this is self.computed: <class 'numpy.ndarray'>
[ 0.06915158  0.08390216  0.08112738 ... -0.06850582 -0.11578567
 -0.10785984]
this is self.computed: <class 'numpy.ndarray'>
[-0.22838798 -0.26693213 -0.1639778  ... -0.06547733 -0.0614232
 -0.04168

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.28029865 0.35510767 0.28804076 ... 0.5100977  0.6009016  0.4742286 ]
this is self.computed: <class 'numpy.ndarray'>
[0.4528902  0.53568023 0.45580053 ... 0.22160032 0.21737462 0.1487925 ]
this is self.computed: <class 'numpy.ndarray'>
[-0.08616343 -0.12880301 -0.13250987 ... -0.03832231 -0.03978804
 -0.02959232]
this is self.computed: <class 'numpy.ndarray'>
[0.08877298 0.13681942 0.14342499 ... 0.24711573 0.32751966 0.2654643 ]
this is self.computed: <class 'numpy.ndarray'>
[0.00114131 0.03103683 0.07023021 ... 0.11427224 0.0890439  0.05004366]
this is self.computed: <class 'numpy.ndarray'>
[-0.02750174 -0.03389612 -0.03142731 ...  0.32633942  0.40351516
  0.31811112]
this is self.computed: <class 'numpy.ndarray'>
[ 0.13722613  0.14725687  0.09698306 ... -0.17312467 -0.18034193
 -0.13072214]
this is self.computed: <class 'numpy.ndarray'>
[ 0.36906493  0.43174827  0.36901963 ... -0.0241868  -0.03124025
 -0.02424565]
this

MoviePy - Done.
MoviePy - Writing audio in temporary/clip2.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip3.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip4.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip5.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip6.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip7.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip8.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip9.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip10.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip11.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip12.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip13.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip14.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip15.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip16.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip17.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip18.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip19.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip20.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip21.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip22.mp3


MoviePy - Done.
MoviePy - Writing audio in temporary/clip23.mp3


MoviePy - Done.
this is self.computed: <class 'numpy.ndarray'>
[0.05510626 0.07763337 0.08009638 ... 0.04989696 0.0525539  0.03852711]
this is self.computed: <class 'numpy.ndarray'>
[0.03599556 0.0512719  0.05611556 ... 0.41881368 0.44159985 0.33097127]
this is self.computed: <class 'numpy.ndarray'>
[0.00262567 0.00363638 0.0040769  ... 0.04255109 0.09804485 0.09703273]
this is self.computed: <class 'numpy.ndarray'>
[0.01178513 0.01473386 0.00807067 ... 0.02482537 0.04006164 0.03753145]
this is self.computed: <class 'numpy.ndarray'>
[-0.00741873 -0.00588913  0.0029176  ... -0.17448027 -0.21804428
 -0.18501267]
this is self.computed: <class 'numpy.ndarray'>
[0.16260317 0.21636987 0.22703633 ... 0.03241098 0.05462134 0.04796429]
this is self.computed: <class 'numpy.ndarray'>
[-0.07180373 -0.08708066 -0.07904871 ... -0.00126898  0.0291595
  0.04465817]
this is self.computed: <class 'numpy.ndarray'>
[ 0.04933608  0.06988586  0.06907898 ... -0.08756738 -0.11030848
 -0.08667521]
this is self

In [13]:
# Step 4: Compare predicted vs. correct maqams
correct_count = sum(1 for true, pred in zip(y_correct, y_pred) if true == pred)
accuracy = correct_count / len(y_correct)
print(accuracy)

0.28


In [9]:
y_correct

translate = {
    'بيات': 'Bayat',
    'حجاز': 'Hejaz',
    'راست': 'Rast',
    'سيكاه': 'Seekah',
    'صبا': 'Saba',
    'عجم': 'Ajam',
    'كرد': 'Kurd',
    'نهاوند': 'Nahawand'
}
y_correct =  [translate[maqam] for maqam in y_correct]
print(y_correct)

['Kurd', 'Bayat', 'Rast', 'Hejaz', 'Seekah', 'Nahawand', 'Nahawand', 'Saba', 'Bayat', 'Rast', 'Hejaz', 'Bayat', 'Rast', 'Bayat', 'Nahawand', 'Rast', 'Bayat', 'Nahawand', 'Hejaz', 'Bayat', 'Nahawand', 'Rast', 'Hejaz', 'Nahawand', 'Bayat', 'Bayat', 'Hejaz', 'Bayat', 'Bayat', 'Bayat', 'Nahawand', 'Hejaz', 'Seekah', 'Bayat', 'Bayat', 'Bayat', 'Seekah', 'Ajam', 'Hejaz', 'Hejaz', 'Hejaz', 'Seekah', 'Hejaz', 'Bayat', 'Ajam', 'Nahawand', 'Nahawand', 'Nahawand', 'Bayat', 'Rast']


In [11]:
print(sampled_files)

['surah22_part1.mp3', 'surah56_part1.mp3', 'surah11_part7.mp3', 'surah19_part2.mp3', 'surah72_part1.mp3', 'surah96_part1.mp3', 'surah11_part6.mp3', 'surah26_part1.mp3', 'surah108_part1.mp3', 'surah28_part6.mp3', 'surah9_part13.mp3', 'surah83_part2.mp3', 'surah67_part1.mp3', 'surah2_part8.mp3', 'surah52_part2.mp3', 'surah42_part1.mp3', 'surah21_part3.mp3', 'surah51_part2.mp3', 'surah36_part2.mp3', 'surah39_part6.mp3', 'surah35_part2.mp3', 'surah14_part5.mp3', 'surah70_part1.mp3', 'surah55_part3.mp3', 'surah4_part5.mp3', 'surah57_part1.mp3', 'surah57_part2.mp3', 'surah112_part1.mp3', 'surah31_part1.mp3', 'surah73_part1.mp3', 'surah38_part3.mp3', 'surah20_part3.mp3', 'surah9_part14.mp3', 'surah12_part6.mp3', 'surah28_part1.mp3', 'surah7_part3.mp3', 'surah6_part6.mp3', 'surah3_part6.mp3', 'surah6_part5.mp3', 'surah25_part6.mp3', 'surah80_part1.mp3', 'surah2_part11.mp3', 'surah22_part4.mp3', 'surah113_part1.mp3', 'surah2_part10.mp3', 'surah32_part3.mp3', 'surah7_part7.mp3', 'surah18_part6.m

In [12]:
print(sampled_labels)

['surah22_part1.mp3.json', 'surah56_part1.mp3.json', 'surah11_part7.mp3.json', 'surah19_part2.mp3.json', 'surah72_part1.mp3.json', 'surah96_part1.mp3.json', 'surah11_part6.mp3.json', 'surah26_part1.mp3.json', 'surah108_part1.mp3.json', 'surah28_part6.mp3.json', 'surah9_part13.mp3.json', 'surah83_part2.mp3.json', 'surah67_part1.mp3.json', 'surah2_part8.mp3.json', 'surah52_part2.mp3.json', 'surah42_part1.mp3.json', 'surah21_part3.mp3.json', 'surah51_part2.mp3.json', 'surah36_part2.mp3.json', 'surah39_part6.mp3.json', 'surah35_part2.mp3.json', 'surah14_part5.mp3.json', 'surah70_part1.mp3.json', 'surah55_part3.mp3.json', 'surah4_part5.mp3.json', 'surah57_part1.mp3.json', 'surah57_part2.mp3.json', 'surah112_part1.mp3.json', 'surah31_part1.mp3.json', 'surah73_part1.mp3.json', 'surah38_part3.mp3.json', 'surah20_part3.mp3.json', 'surah9_part14.mp3.json', 'surah12_part6.mp3.json', 'surah28_part1.mp3.json', 'surah7_part3.mp3.json', 'surah6_part6.mp3.json', 'surah3_part6.mp3.json', 'surah6_part5.